--- Configuration for Flashlight Module.
-- @configuration Flashlight
--- This table defines the default settings for the Flashlight Module.
-- @realm shared
-- @table Configuration
-- @field FlashlightEnabled Indicates whether the flashlight feature is enabled | **bool**
-- @field FlashlightNeedsItem Indicates whether a specific item is required to use the flashlight | **bool**
-- @field FlashlightCooldown The cooldown time in seconds between flashlight uses | **number**
-- @field FlashlightItems A list of items that can be used as flashlights | **table**
