MODULE.name = "Extended Descriptions"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.version = "Stock"
MODULE.desc = "This Module focuses on adding Extended Descriptions."
