MODULE.name = "Realistic 1st Person View"
MODULE.author = "76561198312513285"
MODULE.discord = "@liliaplayer"
MODULE.version = "Stock"
MODULE.desc = "Adds an realistic 1st Person View that allows to see the entire body."
