ITEM.name = "suitcasebomb."
ITEM.desc = "A powerful hidden explosive device."
ITEM.model = ""
ITEM.class = ""
ITEM.weaponCategory = "grenade"
ITEM.width = 2
ITEM.price = 2000
ITEM.height = 2
ITEM.flag = "Y"
