name: CI

on: [push, pull_request]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Lilia Repository
        uses: actions/checkout@v3
        with:
          path: hl2rp

      - name: Setup Lua Environment
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.2"

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.0.0

      - name: Pull GLuaCheck
        uses: actions/checkout@v3
        with:
          repository: LiliaFramework/GluaCheck
          path: luacheck

      - name: Build GLuaCheck
        working-directory: luacheck
        run: luarocks make

      - name: Run GLuaCheck Linter
        working-directory: hl2rp
        run: |
          luacheck . --no-redefined \
            --no-global --no-self \
            --no-max-line-length --no-max-code-line-length \
            --no-max-string-line-length --no-max-comment-line-length \
            --no-max-cyclomatic-complexity

  prettyprint:
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Checkout Lilia Repository
        uses: actions/checkout@v3
        with:
          path: hl2rp

      - name: Download and Install GLuaLint
        run: |
          curl -L -o glualint.zip https://github.com/FPtje/GLuaFixer/releases/download/1.29.0/glualint-1.29.0-x86_64-linux.zip
          unzip glualint.zip -d glualint_folder
          chmod +x glualint_folder/glualint
          sudo mv glualint_folder/glualint /usr/local/bin
          rm -rf glualint.zip glualint_folder

      - name: Run GLuaLint for Pretty Printing
        working-directory: hl2rp
        run: glualint --pretty-print .

      - name: Configure Git
        run: |
          git config --global user.email "githubactions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.LiliaGitSecret }}
        working-directory: hl2rp
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Pretty Printed"
            git push https://${{ secrets.LiliaGitSecret }}@github.com/${{ github.repository }}.git main
          else
            echo "No changes to commit"
          fi